/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the `getopt_long' function. */
#define HAVE_GETOPT_LONG 1

/* Define if you have libdb */
#define HAVE_LIBDB 1

/* Define to 1 if you have the `nsl' library (-lnsl). */
#define HAVE_LIBNSL 1

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define if you want SSL support */
#define HAVE_LIBSSL 1

/* Name of package */
/* #define PACKAGE "isync" */

/* Define to the address where bug reports for this package should be sent. */
/* #define PACKAGE_BUGREPORT "" */

/* Define to the full name of this package. */
/* #define PACKAGE_NAME "" */

/* Define to the full name and version of this package. */
/* #define PACKAGE_STRING "" */

/* Define to the one symbol short name of this package. */
/* #define PACKAGE_TARNAME "" */

/* Define to the version of this package. */
/* #define PACKAGE_VERSION "" */

/* Version number of package */
/* #define VERSION "0.9.1" */
